### ISSUE TITLE
2.0127 seems to be missing documentation

### ISSUE THREAD

**Issue by pghmcfc** [shlomif/perl-XML-LibXML#3] opened 2016-07-23 20:29 UTC
Most of the pod files shipped in previous releases are missing from 2.0127. I suspect that's not intentional.
https://metacpan.org/diff/file?target=SHLOMIF%2FXML-LibXML-2.0127%2F&source=SHLOMIF%2FXML-LibXML-2.0126%2F

A consequence of this is that their manpages don't get installed, including the main XML::LibXML one.

**Comment by shlomif** [comment] 2016-07-24 09:22
Thanks for the report! No, it was not intentional and was caused by ExtUtils::Manifest over-permissive behaviour which didn't properly fail on these files’ absence. This should be fixed in XML-LibXML-2.0128.

**Closed by shlomif** 2016-07-24 09:22 UTC
